---
title: "Programming in Python: Lecture 1"
output: html_document
---

```{r}
library(knitr)
opts_chunk$set(engine = 'python',engine.path="/usr/local/bin/python2")
getwd()
```

Today we'll go over Python's atomic types and basic data structures.

<h3>Getting started</h3>

In this class, we're using Python 2.7. 

If you haven't already installed it, you should go to https://www.python.org/downloads and do so now.

You can write Python and run it using the Python IDLE, but to write programs and save them, you'll need to use a text editor.

I use Sublime Text, which is free and multi-purpose.

<h3>Language properties</h3>

Python is intepreted and dynamically typed (like R!)

<h3>Data Types</h3>

<h4>Integers</h4>

```{python}
x = 10
print x
print type(x)
```

<h4>Floats</h4>

Python has another numeric datatype, which is used for floating point numbers.

```{python}
y = 5.0
print y
print type(y)
```

<h4>Integer and Double Operations</h4>

<h6>Arithmetic operations</h6>

When you divide a float by a float, you get a float.

```{python}
y = 21.0
x = 5.0
z = y/x
print z
print type(z)
```

When you divide an integer by an integer, you get an integer.

```{python}
y = 21
x = 5
z = y/x
print z
print type(z)
```

However, converting an integer to a float is very easy.

<h6>Type conversion</h6>

```{python}
x = 5
y = float(x)
print type(y)
```

<h4>Booleans</h4>

```{python}
x = True
y = False
print x,y
```

<h4>Boolean operations</h4>

<h6>Equality testing</h6>

```{python}
x = True
y = False
print x == y
```

<h6>Negation</h6>

```{python}
x = True
y = False
print x != y
print not (x == y)
print (not x) == y
```

<h6>Conjunction and Disjunction</h6>

```{python}
print (True or False) == True
print (True and False) == True
```

<h4>Comparing numeric types</h4>

```{python}
i = 5
j = 5.0
print j == i
print j > i
print j <= i
```

<h4>Strings</h4>

Python is great for string-processing!

```{python}
cat = "Captain Haddock"
print cat
```

Often, we want to know the length of the string we're dealing with.

```{python}
print len("cat")
```
One helpful feature is being able to slice strings.

*Important note*: Unlike R, Python indexes starting at 0.

```{python}
yummy = "marshmallow"
gummy = yummy[0:5]
print gummy
```

Another common task is finding substrings.

```{python}
yummy = "marshmallow"
gummy = "marsh"
print gummy in yummy
```

We can also build up longer strings through concatenation.

```{python}
fish = "Haddock"
title = "Captain"
cat = title+" "+fish
print cat
```

We can divide a string by a specified character using split.

```{python}
cat = "Captain Haddock"
print cat.split(" ")
```

The object returned by split() is a list of strings.

<h4>Lists</h4>

Python lists can hold heterogenous data types.

```{python}
cat_data = [5,"Captain Haddock","Calvin",11,True]
print cat_data
print type(cat_data[0])
```

Notice that the contents of a list can be indexed just like strings. We can also take slices of lists.

```{python}
cat_data = [5,"Captain Haddock","Calvin",11,True]
cats = cat_data[1:3]
print cats
```

There are all kinds of useful list operations. But the most important to know for now is how to add new items.

```{python}
cats = ["Captain Haddock","Calvin"]
cats.append("Jane")
print cats
```

You can also add all items in a list to another list using extend()

```{python}
blackCats = ["Captain Haddock","Smurfie"]
moreBlackCats = ["Carbon","Jane"]
blackCats.extend(moreBlackCats)
print blackCats 
```

We can remove items by name using delete().

```{python}
cats = ["Captain Haddock","Calvin","Jane"]
cats.remove("Jane")
print cats
```

Notice that we did not have to save the result of append() or remove() as a list. These methods do not return anything; they update the list in place.

We can also remove them by position using pop()

```{python}
cats = ["Captain Haddock","Calvin","Jane"]
print cats.pop(0) 
print cats
```

This way of removing items does return something: the item that is removed.

There is also a built-in sort method for lists, which likewise sorts in place.

```{python}
cats = ["Captain Haddock","Smurfie","Calvin","Jane"]
cats.sort()
print cats
```

<h4>Tuples</h4>

Tuples are sort of like lists, because they store things. 

```{python}
friends = ("Calvin","Captain Haddock")
print type(friends)
```

Unlike lists, however, tuples are immutable: you can't change their contents. You can index into a tuple, but you cannot reassign a position in a tuple.

```{python}
friends = ("Calvin","Captain Haddock")
print friends[0]
#friends[0] = "Smurfie"
```

You can also construct tuples through *tuple packing*.

```{python}
friends = "Calvin", "Captain Haddock"
print friends
```

Similarly, you can name the items of a tuple through *sequence unpacking*.

```{python}
friends = "Calvin", "Captain Haddock"
Calvin, Haddock = friends
print Calvin
print Haddock 
```

<h3>Control Statements</h3>

<h4>If statements</h4>

The most common type of control statement is the *if* statement.

```{python}
x = 5
y = 7
if y > x:
  print "Y is bigger!"
else:
  print "X is bigger!"
```

Python is *white-space sensitive*. If you don't indent correctly, you will get an error.

If you have more than one if/else statement to chain, you should use *elif*.

```{python}
x = 7
y = 7
if y > x:
  print "Y is bigger!"
elif x > y:
  print "X is bigger!"
else:
  print "X and Y are equal!"
```

<h4>For statements</h4>

Another common type of control statement is the for loop.

```{python}
cats = [("Calvin",11,"butter"),("Captain Haddock",5,"rabbit")]
for cat in cats:
  name = cat[0]
  age = cat[1]
  favoriteFood = cat[2]
  print name+"'s favorite food is "+favoriteFood+". He is "+str(age)+" years old."
```

That last line was a little awkward. There's a nicer way to print strings using Python fancy string formatting.

<h3>Fancy string formatting</h3>

```{python}
cats = [("Calvin",11,"butter"),("Captain Haddock",5,"rabbit")]
for cat in cats:
  name = cat[0]
  age = cat[1]
  favoriteFood = cat[2]
  print "{0}'s favorite food is {1}. He is {2} years old.".format(name,favoriteFood,age)
```

With fancy strings, we can supply all variables as arguments to format() instead of using concatenate to build up a string.

<h3>Reading data in from a file</h3>

The last topic we'll cover today is reading data in from a file. To do this, we need to import the sys library.

Next, we open the file using open(), and specify whether we are reading ("r") or writing ("w") from the file using the second argument to open().

```{python}
import sys
f = open("/Users/carolyn/Documents/UMass/CogMod/Ling692c/searchlist.txt","r")
wordlist = f.read()
print wordlist
```

<h3>Exercise</h3>

I've generate a word search using the misc.wordfinder in the NLTK library. NLTK has lots of useful modules for computational linguistics--- it's worth downloading and exploring.

Your first task, though, is simply to figure out how to print the word search puzzle nicely. 

```{python}
import sys

gridFile = open("/Users/carolyn/Documents/UMass/CogMod/Ling692c/grid.txt","r")
gridText = gridFile.read()

grid = gridText.split(",")

for line in grid:
  newline = ""
  for letter in line:
    newline = newline+" "+letter
  print newline

f = open("/Users/carolyn/Documents/UMass/CogMod/Ling692c/searchlist.txt","r")

wordlist = f.read()
for w in wordlist.split(","):
  print w
```

<h6>Bonus exercise</h6>

Can you come up with a way of finding words in the word search puzzle?

```{python}
import sys

gridFile = open("/Users/carolyn/Documents/UMass/CogMod/Ling692c/grid.txt","r")
gridText = gridFile.read()

grid = gridText.split(",")

f = open("/Users/carolyn/Documents/UMass/CogMod/Ling692c/searchlist.txt","r")
wordlist = f.read()
wordlist = wordlist.split(",")

#Vertical
for line in grid:
  for w in wordlist:
    if w in line or w[::-1] in line:
      print "Found {0}!".format(w)

#Horizontal
columns = []
for i in range(0,20):
  columns.append("")
for line in grid:
  for i in range(0,len(grid)):
    columns[i] = columns[i]+line[i]

for c in columns:
  for w in wordlist:
    if w in c or w[::-1] in c:
      print "Found {0}!".format(w)
```