---
title: 'Programming in Python: Lecture 4'
author: "Carolyn Jane Anderson"
date: "9/27/2017"
output: html_document
---

Today is a bit of a hodgepodge. We're going to talk about scope. We'll also discuss debugging.

```{r,echo=FALSE}
library(knitr)
opts_chunk$set(engine = 'python',engine.path="/usr/local/bin/python2")
```

<h3>Warm-up: complex onsets in English</h3>

Task: write a regex that recognizes licit complex onsets in English using the simplified sonority sequencing hierarchy.

Glides > Liquids > Nasals > Fricatives/ Affricates > Plosives

[y j w] > [r l] > [m n] > [z v th f ch s sh] > [b d g p t k]

(We'll work with English orthography rather than IPA since the way Python handles Unicode varies between 2.7 and 3.)

Once you have your regex, try to write a program that compares your regex's classification with the list of words in good_onsets.txt.

What words does your regex classify as good that are not in good_onsets.txt?

What words in good_onsets.txt does your regex fail to classify?

<h2>Scope</h2>

So far, we haven't explicitly discussed scope. As you've probably figured out by now, variables declared within a function are bound within the scope of that function, even if they share the same name as a variable outside of the function.

```{python}
x = 3

def foo():
  x = 7

foo()
print x
```

Similarly, if you modify the value of a variable inside a function, its value outside the function will not be affected.

```{python}
x = 3

def foo(y):
  y = y+7  #We could return y and update x with the result of foo(x) in order to affect the value of x in the outer context.

foo(x)
print x
```

However, more care must be taken with mutable datatypes. Datatypes like lists have methods that modify the list in place. It's important to be aware that the calling these methods inside a function will affect the value of the datatype outside the function as well.

```{python}
l = ["b","z","a"]

def foo(s):
  s.sort()

foo(l)
print l
```

What if you want to be able to reference a variable no matter what the local scope is?

You can create a *global variable* that is accessible, well, globally. However, it's easy to create errors through the misuse of global variables, and it's generally good style to try to avoid them, since they complicate the logic of your program. 

<h2>Debugging</h2>

Good debugging practice relies on good programming practice. Debugging is only necessary when we fail. In an ideal world, we'd write perfect code that runs on the first try. Since we don't like to think we're going fail, it's easy to fool ourselves into thinking we don't have to write code that is easy to debug. 

What I mean when I say that good debugging is mostly good programming is that debugging becomes much easier when your code is:

<b>Planned</b>: you have at least an outline, on a whiteboard or preferably on paper, breaking the problem into steps

<b>Modular</b>: broken into small, testable sub-functions

<b>Commented</b>: with the input, output, and expected functionality of each function, and explanations of any particularly tricky lines

<b>Conventionally-styled</b>: with informative variable names, plenty of whitespace (it's free!), and an easy-to-find main()

<h4>Planning</h4>

This is the most important step of programming. First, take the time to sketch out a plan for your program, on a whiteboard or preferably on paper. Start with the input and the output. Think about input/output pairs and what needs to happen in the middle of your program to produce them.

List out desiderata for your program: how is your program receiving the input? what data structures will you use to store the input and intermediate forms? what should the output of your program look like?

Next, break your program into functions. At this point, you can open a python file if you like. Write a comment at the top based on the desiderata you wrote down. Create your functions in stubbed form. This means you define the function and write a comment explaining its purpose, but leave it unimplemented for now. Have it return nothing (or None).

For core functions, you may want to sketch out their structure on paper before implementing them too. Think through a few different inputs. What should your function return?

Here's an example of a program written without much consideration.

```{python}

def scale(bag1,bag2):
  print("Bag A: "+bag1+" Bag B: "+bag2)
  a, b = int(bag1), int(bag2)
  if a+b <= 46 and a <= 23 and b <= 23:
    print("You are good to fly!")
  elif a+b > 46 and a>23 and b>23: 
    print("You have too much packed.\nYou need to unpack " + str(a+b - 46)+"kg.")
  elif a>23 and a-23 > 23-b:
    print("You have too much packed.\nYou need to unpack " + str(a - 23)+"kg.")
  elif b>23 and b-23 > 23-a:
    print("You have too much packed.\nYou need to unpack " + str(b - 23)+"kg.")
  elif a > 23:
    print("Bag 1 is too heavy.\nRebalance " + str(a-23)+"kg into bag 2.")
  else:
    print("Bag 2 is too heavy.\nRebalance " + str(b-23)+"kg into bag 1.")
  
scale("20","12") #Both bags light enough
scale("25","27") #Both are too full
scale("23", "25") #B is too full
scale("25", "23") #A is too full

scale("25", "21") #A is too full but B has space
scale("20", "26") #B is too full but A has space

#Example courtesy of the /r/badcode/ subreddit
```

Can anyone spot the redundancy?

Let's think through the possible input to the program. 

First, both Bag 1 and Bag 2 may be under the 23kg weight limit.

Second, Bag 1 may be too heavy, but there is still space in Bag 2.

Third, Bag 2 may be too heavy, but there is still space in Bag 1.

Last, the total baggage may be over 46 because one bag is too heavy, and there's not enough room in the other for the excess.

```{python}

def scale(bag1,bag2):
  print("Bag A: "+bag1+" Bag B: "+bag2)
  a, b = int(bag1), int(bag2)
  if a <= 23 and b <= 23: #If both bags are light enough
    return("You are good to fly!")
  else:
    if a+b > 46: #Too much baggage overall
      return("You have too much packed.\nYou need to unpack " + str(a+b - 46)+"kg.")
    elif a > 23:
      return("Bag 1 is too heavy.\nRebalance " + str(a-23)+"kg into bag 2.")
    else:
      return("Bag 2 is too heavy.\nRebalance " + str(b-23)+"kg into bag 1.")
    
print scale("20","12"), "\n" #Both bags light enough
print scale("25","27"), "\n" #Both are too full
print scale("23", "25"), "\n" #B is too full
print scale("25", "23"), "\n" #A is too full
print scale("25", "21"), "\n" #A is too full but B has space
print scale("20", "26"), "\n" #B is too full but A has space
```

<h4>Modularity</h4>

Modularity leads to easier debugging for two reasons. 

First, it's usually easier to understand things that are broken into pieces. Here's how I originally found the baggage example that we saw above:

```{python}
bag1 = "50"; bag2 = "30"; a, b = int(bag1), int(bag2); print("You are good to fly!" if a+b <= 46 and a <= 23 and b <= 23 else ("You have too much packed.\nYou need to unpack " + str(a+b - 46)+"kg." if a+b > 46 else ("Bag 1 is too heavy.\nRebalance " + str(a-23)+"kg into bag 2." if a > 23 else "Bag 2 is too heavy.\nRebalance " + str(b-23)+"kg into bag 1.")))
```

```{python}
#Better

bag1 = "50"
bag2 = "30"
a, b = int(bag1), int(bag2)

if a+b <= 46 and a <= 23 and b <= 23: #Still some redundancy here
  print("You are good to fly!")
elif a+b > 46:
  print("You have too much packed.\nYou need to unpack " + str(a+b - 46)+"kg.")
elif a > 23:
  print("Bag 1 is too heavy.\nRebalance " + str(a-23)+"kg into bag 2.")
else:
  print("Bag 2 is too heavy.\nRebalance " + str(b-23)+"kg into bag 1.")
```

Second, if you break your program up into small functions, it will be easier to test incrementally. Every time you write a function, you should test it out on at least a handful of input to make sure it is performing correctly.

Of course, modularity is also helpful if you decide to change part of your program, or reuse part of your code in another program. It's easier to do that if you've written it as a separate function.

<h4>Commenting</h4>

Here's a situation you don't want to be in. You've written a beautiful project in Python that relies on several different files. You decide you want to upload it to Github, so other people can use it, and you think, "I should make sure all my files are commented, so that people can understand them."

It's been a few months since you wrote the code, though, and this is what you see when you open one of your files:

```{python, eval=FALSE}
def oo000 ( ) :
 ii = 12
 for ii in range ( 0 , ii ) :
  print oOOo ( ii )
  if 59 - 59: Oo0Ooo . OO0OO0O0O0 * iiiIIii1IIi . iII111iiiii11 % I1IiiI
def oOOo ( n ) :
 if n <= 1 :
  if 27 - 27: iIiiiI1IiI1I1 * IIiIiII11i * IiIIi1I1Iiii - Ooo00oOo00o
  if 48 - 48: oO0o / OOooOOo / I11i / Ii1I
  return n
 else :
  return ( oOOo ( n - 1 ) + oOOo ( n - 2 ) )
  if 48 - 48: iII111i % IiII + I1Ii111 / ooOoO0o * o00O0oo
oo000 ( ) 
```

Can anyone guess what this does? Yeah, you can't either, even though you wrote it. 

If you do, by chance, inherit some legacy code, the first thing you should do is go through it, read all the comments, and put in comments as you start to understand things. At first, the code might look like:

```{python, eval=FALSE}
def oo000 ( ) :
 ii = 12 #Sets variable ii to 12
 for ii in range ( 0 , ii ) : 
  print oOOo ( ii )
  if 59 - 59: Oo0Ooo . OO0OO0O0O0 * iiiIIii1IIi . iII111iiiii11 % I1IiiI #Does this even do anything??
def oOOo ( n ) : #Function
 if n <= 1 :
  if 27 - 27: iIiiiI1IiI1I1 * IIiIiII11i * IiIIi1I1Iiii - Ooo00oOo00o
  if 48 - 48: oO0o / OOooOOo / I11i / Ii1I
  return n
 else :
  return ( oOOo ( n - 1 ) + oOOo ( n - 2 ) ) #Returns ... ??
  if 48 - 48: iII111i % IiII + I1Ii111 / ooOoO0o * o00O0oo
oo000 ( ) 
```

But that's ok. Just make sure you search for '?' before you let anyone else see the code.

<h4>Well-styled code</h4>

Part of what makes this code so difficult to understand is that it ignores normal programming conventionally.

It's good practice to use informative variable names. The variable names in this program don't tell us anything about the values that they store. Let's do some renaming.

First, I'll call the top function main(), since it's called at the bottom of the program.

Next, I'll rename ii to i, since that's a conventional name for a throw-away variable in for-loop.

```{python}
def main():
 iterations = 12 
 for i in range (0, iterations): #Calls function foo() 12 times and prints the result
  print foo(i)
  if 59 - 59: Oo0Ooo . OO0OO0O0O0 * iiiIIii1IIi . iII111iiiii11 % I1IiiI #Does this even do anything??
def foo(n) : #We still don't know what this does, so we'll call it foo
 if n <= 1 :
  if 27 - 27: iIiiiI1IiI1I1 * IIiIiII11i * IiIIi1I1Iiii - Ooo00oOo00o
  if 48 - 48: oO0o / OOooOOo / I11i / Ii1I
  return n
 else :
  return ( foo( n - 1 ) + foo( n - 2 ) ) #Returns ... ??
  if 48 - 48: iII111i % IiII + I1Ii111 / ooOoO0o * o00O0oo
main( ) #We'll call this main, since it's called at the bottom
```

To clean the code up any more, we'll need to understand what the program actually does. When we it, it looks like it calculates the first 12 Fibonocci numbers.

```{python}
def main():
 iterations = 12 
 for i in range (0, iterations): #Calls function fib() 12 times and prints the result
  print fib(i)
  if 59 - 59: Oo0Ooo . OO0OO0O0O0 * iiiIIii1IIi . iII111iiiii11 % I1IiiI #Does this even do anything??
def fib(n) : #We still don't know what this does, so we'll call it foo
 if n <= 1 : #Base case
  if 27 - 27: iIiiiI1IiI1I1 * IIiIiII11i * IiIIi1I1Iiii - Ooo00oOo00o
  if 48 - 48: oO0o / OOooOOo / I11i / Ii1I
  return n
 else : #Recursively call fib on the numbers 1 less and 2 less than current number to calculate result
  return ( fib( n - 1 ) + fib( n - 2 ) ) #Returns ... ??
  if 48 - 48: iII111i % IiII + I1Ii111 / ooOoO0o * o00O0oo
main( )
```

What about all those *if n - n:* statements? Let's comment them out and see what happens.

```{python}
def main():
 iterations = 12 
 for i in range (0, iterations): #Calls function fib() 12 times and prints the result
  print fib(i)
  #if 59 - 59: Oo0Ooo . OO0OO0O0O0 * iiiIIii1IIi . iII111iiiii11 % I1IiiI #Does this even do anything??
def fib(n) : #Calculates the nth number in the Fibonocci sequence
 if n <= 1 : #Base case
  #if 27 - 27: iIiiiI1IiI1I1 * IIiIiII11i * IiIIi1I1Iiii - Ooo00oOo00o
  #if 48 - 48: oO0o / OOooOOo / I11i / Ii1I
  return n
 else : #Recursively call fib on the numbers 1 less and 2 less than current number to calculate result
  return ( fib( n - 1 ) + fib( n - 2 ) ) #Returns a number in the fibonnoci sequence
  #if 48 - 48: iII111i % IiII + I1Ii111 / ooOoO0o * o00O0oo
main( )
```

Yeah, nothing. First, notice that some of them occur after a return statement. That's a pretty good indication that they're junk, because once a value is returned, nothing else in the function is evaluated.

Second, these statements boil down to *if 0:*. 0 evaluates to False, which means that these if-statements will never run.

```{python}
def main():
 iterations = 12 
 for i in range (0, iterations): #Calls function fib() 12 times and prints the result
  print fib(i)
def fib(n) : #Calculates the nth number in the Fibonocci sequence
 if n <= 1 : #Base case
  return n
 else : #Recursively call fib on the numbers 1 less and 2 less than current number to calculate result
  return ( fib( n - 1 ) + fib( n - 2 ) ) #Returns the nth number in the Fibonnoci sequence
main( )
```

<h3>Okay, yeah, but how do I actually debug?</h3>

The most basic debugging tool is the copious use of print statements. You should use print statements liberally as you write coe to check that your code is doing what you expect.

Second, if you're writing a program that runs on large input files, you should create some smaller test files with just a handful of data points. Then you can manually check the output that your program produces.

Another debugging strategy is to think by *cases*. This means thinking about how your program behaves when given different kinds of input. In a string-processing function, for instance, it's common to treat the empty string a little differently than other input. In a recursive function, you will have a base case: on some input, the function returns a value instead of calling itself. Without a base case, a recursive function will not terminate.

```{python}
#A program that prints a countdown from 10 to "Blast off!".

def countDown(n): #A recursive function that prints a countdown from n to "Blast off!"
  if n == 0:
    print "Blast off!"
    #countDown(n-1) If we uncomment this line, our function will not terminate
  else:
    print n
    countDown(n-1)

countDown(10)
```

Professional software developers often use test suites: programs that define a whole bunch of test cases for the system. It's sort of like installing smoke alarms: failing test cases that you've previously passed indicates that you've introduced some bugs into the program.

Writing a formal test suite is overkill for most of what you will be doing. But, you can still use the idea of test cases to verify that your code is performing as expected. 

```{python}
import re

def search(r,line):
	res = re.search(r,line)
	if res is not None:
	  if type(res) == type(None): #Make sure res isn't None
	    print "None!"
	  return line
	else:
	  if type(res) != type(None):
	    print "Not None!" #Make sure None is None
	  return False

#r = re.compile(r'^[bdgptk]*[zv(th)fchs(sh)]*[mn]*[rl]*[yjw]*[aeiou]+')
r = re.compile(r'^[yjw]*[rl]*[mn]*[zv(th)fchs(sh)]*[bdgptk]*[aeiou]+')

if search(r,"lbib") != False: #Check on input "lbib"
  print "False positive!"
if search(r,"trip") != "trip": #Check on input "trip"
  print "False negative!"
```


<h2>Let's practice!</h2>
