---
title: 'Programming in Python: Lecture 5'
author: "Carolyn Jane Anderson"
date: "10/11/2017"
output: html_document
---

Today we're going to talk about efficiency.

```{r,echo=FALSE}
library(knitr)
opts_chunk$set(engine = 'python',engine.path="/usr/local/bin/python2")
```

<h2>Warm-up</h2>

<h4>Task: write an program that asks the user for a number n and prints a
multiplication table with n lines and columns.</h4>

It should compute the value I*J in line I and column J.

For example, for n=5, your program should output the following:

```
1 2  3  4  5
2 4  6  8  10
3 6  9  12 15
4 8  12 16 20
5 10 15 20 25
```


<h2>Efficiency</h2>

<h3>Why efficiency?</h3>

Efficiency matters because it is a pain to sit around waiting for your program to finish. So far, the programs we've tackled in this class have been simple enough that efficiency hasn't really mattered. However, as you work with larger input files and more complicated algorithms, the speed of your program and the amount of memory it uses can become real concerns. 

<h3>How do we measure efficiency?</h3>

+Speed

+Memory use

+Actions per input

When we're analyzing an algorithm, we want to discuss efficiency abstracted away from the actual input to the program. Both speed and memory generally depend on the size of the input. However, we want to understand the relation between the efficiency of the algorithm and the input size.

Generally, then, computational efficiency is measured in how many actions are taken per input. This gives us a measure of efficiency that does not depend on the size of the input. It also allows us to understand how the efficiency of the program changes as the input size changes.

<h2>Activity: Sorting a List</h2>

Can you come up with an efficient way of sorting a list of numbers?

<h3>Sorting algorithms</h3>

Let's think through the efficiency of a few different sorting algorithms.

What is the *best case*? What is the *worst case*? How many actions does the algorithm perform on average?

<h4>Insertion sort</h4>

```
for i in range(1,len(list)):
  for j in range(1,i):
    if l[i] is less than l[0]:
      move l[i] 1 to the left
```

What is the best case for Insertion Sort?

It's pretty good! In the best case, the list is already sorted. In that case, we only have to perform 1 comparison for each input. That's called *linear time*.

What happens if the array is sorted in reverse order?

In this case, each item will require n moves to put it in the right place, where n is the size of the list. This means that n^2 operations are required to sort a list of n size.

On average, Insertion Sort has a *quadratic run time*. That's not good.

<h4>Bubble sort</h4>

```
for i in range(0,len(list)):
  for j in range(0,len(list)):
    compare j and j+1
    if out of order, swap
```

Bubble sort is also inefficient! On the first iteration, it requires n-1 comparisons, and in each following iteration, the number of required comparisons decreases by 1.

That works out to be (n-1)(n)/2 comparisons for a list of size n.

Unfortunately, that's still quadratic.

In the best case, however, Bubblesort requires only 1 pass through the data (n-1) comparisons. That's because if Bubblesort doesn't do any swaps in the first iteration, it can quit early.

<h4>Merge sort</h4>

```
def mergesort(l):
  if len(l) > 1:
    return merge(mergesort(l[0:half]),mergesort(l[half:len(l)]))
  else:
    return l

def merge(l1,l2):
  newlist
  while len(l1) > 0 and len(l2) > 0:
    if l1[0] > l2[0]:
      newlist.append(l1[0])
      delete l1[0]
    else:
      newlist.append(l2[0])
      delete l2[0]
  if len(l1) > 0:
    newlist.append(l1)
  elif len(l2) > 0:
    newlist.append(l2)
  return newlist
```

Merge Sort is an example of a divide-and-conquer algorithm. That is, it allows us to break the input into little pieces, work on those pieces, and then stick them back together again. That's usually a good thing.

How efficient is Merge Sort?

Merge Sort is an n log n run time algorithm. 

Merge Sort, unlike Insertion Sort and Bubble Sort, does not sort in place, which means that we must allocate memory for the copies of the smaller parts of the lists that we make.

<h2>Search</h2>

Okay, we have some vocabulary for talking about the efficiency of our algorithms. At this point you may be thinking, "Why do I care about sorting algorithms when quicksort is built into Python lists?"

That's fair. You won't need to write your own sorting functions very frequently. But you do need to understand the basics of efficiency in order to make decisions between Python's built-in features.

Let's take *search* as an example. Now that we understand how to produce lovely sorted lists, how do I go about finding a particular value?

Of course, one way to go about it is to iterate through all the items in a list using a for-loop.

```{python}
list = ["Professor Calculus","Professor Euclide","Aristides Silk","Professor Tarragon","Christopher Willoughby-Drupe","Captain Haddock","Thomson and Thompson","Sophocles Sarcophagus","Snowy"]

for l in range(0,len(list)):
  if list[l] == "Snowy":
    print l
```

In the worst case, this involves iterating through the entire list!

There's also a built-in method for lists to look up particular values.

```{python}
list = ["Professor Calculus","Professor Euclide","Aristides Silk","Professor Tarragon","Christopher Willoughby-Drupe","Captain Haddock","Thomson and Thompson","Sophocles Sarcophagus","Snowy"]
print list.index("Snowy")
```

Is this more efficient?

Well, maybe. Generally, the built-in functions will be faster than what you would right yourself, because they're often optimized in subtle ways. However, there's really no way to get around the fact that you don't know where in the list the item is. 

The complexity of Get Item for lists is still linear time--- that is, you may have to search the entire list to find the item.

You can check the complexity of built-in methods here: https://wiki.python.org/moin/TimeComplexity

<h4>So what's the solution?</h4>

Well, maybe you can reshape your problem. 

Is there a way to look up by position, rather than by value?

Looking up an item in a list by position is a constant-time operation.

Are you iterating through a list once for each entry?

Maybe you should go through the list once, in order, and read the items into a dictionary.

Dictionaries allow you to look up items by value in constant-time--- that's really what they're designed for.

<h2>Exercise: what is the efficiency of the program you wrote for the warm-up?</h2>
