---
title: 'Programming in Python: Lecture 6'
author: "Carolyn Jane Anderson"
date: "10/19/2017"
output: html_document
---

```{r,echo=FALSE}
library(knitr)
opts_chunk$set(engine = 'python',engine.path="/usr/local/bin/python2")
```

Today we're going talk about recursion and functional programming.

<h2>Warmup</h2>

<h2>Recursion</h2>

Recursion is useful because it allows us to employ a divide-and-conquer approach, as we saw last week when looking at sorting algorithms.

We haven't explicitly discussed recursion much in this class, although we've seen a couple examples of recursive programs.

Most of the functions we've worked with so far have been iterative: they iterate through the data to arrive at a solution.

Consider an iterative approach to calculating the factorial of a number. The factorial of 0 is 1. The factorial of n is 1 \* (1+1)...(n-1) * n.

We have to treat 0 as a special case. Then we iterate through all the numbers up to n and iteratively increase the return value, m, by multiplying it by the ith number in the range.

```{python}
def itFactorial(n):
  m = 1
  if n==0:
    return m
  else:
    for i in range(1,n+1):
      m = m*i
  return m

print itFactorial(0)
print itFactorial(3)
```

How would we write this recursively? Well, we have a natural basecase: 0. 

```{python}

def recFactorial(n):
  if n==0:
    return 1
  else:
    return n*recFactorial(n-1)

print recFactorial(0)
print recFactorial(3)
```

In any other case, we call the function recursively to calculate the factorial of n-1, and multiply the result by n.

<h5>So which is better, iterative or recursive?</h5>

Well, it really depends on the application. Sometimes the recursive solution is faster, or easier to reason about (often the case with particular kinds of data structures like trees). Sometimes the iterative solution is more intuitive, or requires less memory.

For instance, both the factorial programs we wrote are pretty simple. But, it turns out that the iterative version requires only O(1) space, while the recursive one takes O(n) space, because the program has to keep track of all the levels of recursion.

What is the time efficiency of each program?

<h2>Functional programming</h2>

<h3>Functions as arguments</h3>

Why is functional programming useful? Let's write a function that iterates through a list of numbers, and returns all the items that are even.

```{python}
def evens(l):
  n = []
  for e in l:
    if e%2.0==0:
      n.append(e)
  return n

nums = [1,20,3.4,11,5.7,25,11.2,22,24,10]
print evens(nums)
```

Wait, oops, we actually need all the *odd numbers*, not the even ones! What to do?

```{python}
def odds(l):
  n = []
  for e in l:
    if e%2.0!=0:
      n.append(e)
  return n
  
nums = [1,20,3.4,11,5.7,25,11.2,22,24,10]
print odds(nums)
```

Great! Later on, we realize we also need to find all the multiples of 4 in the list.

```{python}
def multiplesOfFour(l):
  n = []
  for e in l:
    if e%4.0==0:
      n.append(e)
  return n
  
nums = [1,20,3.4,11,5.7,25,11.2,22,24,10]
print multiplesOfFour(nums)
```

Gosh, it feels like we're writing the same code over and over again! What if instead, we pass that 1 line that's different to our function as an argument?

```{python}

def exclude(l,f):
  n = []
  for e in l:
    if f(e):
      n.append(e)
  return n
  
nums = [1,20,3.4,11,5.7,25,11.2,22,24,10]

def isEven(x):
  return x%2.0==0
  
def isOdd(x):
  return x%2!=0
  
print exclude(nums,isEven)
print exclude(nums,isOdd)
```

Here we've written a function, exclude( ), that takes another function as an argument. This is known as a *higher-order function*.

<h4>Anonymous functions</h4>

In addition to the function declaration style we've worked with previously, Python allows you to write anonymous functions called lambdas. Semantically, they're exactly the same: this is just a more compact syntax.

```{python}
f = lambda x : x*x
print f(5)
```

Lambdas are a convenient shorthand when you don't plan to reuse the function.

```{python}
def foo(f,x):
  if type(x)!=int:
    print "Oh no, it's not an integer!"
  else:
    print f(x)

def f(x):
  return x*x

foo(lambda x: x*x,5)
foo(f,5)
```

In the example above, both calls to foo() produce the same result, but the normal function definition way requires a few lines of code more than the lambda version. (Of course, the normal function definition way allows you to call the function later on in the code, which may be an advantage.)

<h3>Map</h3>

Python provides several functions that make it easy to work with lists in a functional programming style. 

Map( ) takes a function and a list, applies the function to each element, and returns the resulting list.

```{python}
import string

words = ["zither","Gobsmack","funicular","Vernacular","dither","damsel","Damson"]
print map(lambda x:string.lower(x),words)
```

<h3>Reduce</h3>

Reduce( ) also takes a function and a list. However, it applies the function pairwise. In the first step, it will apply the function to the first two items in the list. In all previous steps, it will apply it to the result of the previous computation and the next item in the list. It returns a single value.

In other words, it *reduces* the list down to a single value using the given function.

```{python}
numbers = [1, 2, 3, 4]
letters = ["h","e","l","l","o","!"]
print reduce(lambda x, y: x*y, numbers)
print reduce(lambda x, y: x+y, letters)
```

<h3>Filter</h3>

Filter( ) applies a function to a list, and returns the elements of the list for which the function returns true.

It's a way of filtering out elements of a list that don't satisfy some criteria.

```{python}
numbers = [1, 2, 3, 4]
isEven = lambda x:x%2==0
print filter(isEven,numbers)
```

(Note: % is the modulo operator in Python--- it returns the remainder of dividing the first argument by the second.)

Here we define a function that returns true if the input is even, and false otherwise. Then we apply isEven( ) to the list of numbers using filter( ), and the result is a list containing only even numbers.

<h3>Zip</h3>

Zip turns two lists into a list of tuples.

```{python}
names = ["Hermione","Luna","Pansy","Cho","Millicent","Ginny","Hannah"]
houses = ["Gryffindor","Ravenclaw","Slytherin","Ravenclaw","Slytherin","Gryffindor","Hufflepuff"]
pairs = zip(names,houses)
for p in pairs:
  print p[0], "is in", p[1]
```

Zip( ) can also be used with the * operator to unzip a list of tuples. Given a list of n-ary tuples, it returns n tuples.

You can then use list( ) to convert the tuples it returns into a list.

```{python}
pairs = [('Hermione', 'Gryffindor'), ('Luna', 'Ravenclaw'), ('Pansy', 'Slytherin'), ('Cho', 'Ravenclaw'), ('Millicent', 'Slytherin'), ('Ginny', 'Gryffindor'), ('Hannah', 'Hufflepuff')]
names,houses = zip(*pairs)
print names
print list(houses)
```

Zip is useful when you're reading items into a dictionary.

```{python}
names = ["Hermione","Luna","Pansy","Cho","Millicent","Ginny","Hannah"]
houses = ["Gryffindor","Ravenclaw","Slytherin","Ravenclaw","Slytherin","Gryffindor","Hufflepuff"]
pairs = zip(names,houses)
print dict(pairs)
```

<h3>Join</h3>

Join( ) is a string method that creates a string out of the items of an iterable (like a list).

It is technically a method on the string that is used to separate the items.

```{python}
letters = ["h","e","l","l","o","!"]
print '~'.join(letters)
```

I use it most frequently with an empty string or space character separator.

```{python}
letters = ["h","e","l","l","o","!"]
words = ["hello","world","!"]
print ''.join(letters)
print ' '.join(words)
```

<h3>Practice</h3>

<h4>Problem 1: Find the sum of the list</h4>

Given the list below, can you write a single line of code that returns the sum of all values in the list?

```{python}
numbers = [8523, 2065, 8757, 7000, 4741, 4622, 380, 574, 5011, 220, 8281, 541, 8947, 9750, 8987, 1876, 6760, 4000, 4896, 4099, 8353, 5341, 4979, 7411, 1682, 5362, 5418, 2402, 8235, 5670, 7685, 396, 8070, 3719, 4003, 4107, 8386, 9530, 273, 1963, 2311, 6711, 9854, 4820, 1565, 2907, 9195, 6062, 3179, 9570]
```

<h4>Problem 2: Find the largest value in a list</h4>

Given the same list, can you write a single line of code that returns the largest value?

<h4>Problem 3: Remove False items from list</h4>

Given the list below, can you write a single line of code that removes all Falses?

```{python}
l = [False,"penguin",1,False,True,19,20,"pepper",True,109,"a",False,"peanut","pimento",100,True,109,False]
```

<h4>Problem 4: Find all words containing a given root</h4>

Given the list of words in misc.txt, can you write a single line of code that returns a list of all elements containing the root 'present'?

```{python}
f = file('/Users/carolyn/Documents/UMass/CogMod/Ling692c/lecture 6/misc.txt','r')
print f.read().split('\n')
```



