---
title: 'Programming in Python: Lecture 2'
author: "Carolyn Jane Anderson"
date: "9/15/2017"
output: html_document
---

```{r,echo=FALSE}
library(knitr)
opts_chunk$set(engine = 'python',engine.path="/usr/local/bin/python2")
```

Today we're going to cover input and output, functions, and dictionaries.

<h3>Input and Output</h3>

In our last class, we briefly saw how to open a file and read its contents. We can use the same file() function to write the results of a program to a file. 

```{python}
f = open('results.txt', 'w') #Remember to adjust the name/location of the file for your own computer!
introduction = "Hello!\nMy name is Matilda."
f.write(introduction)
```

This creates a file in my working directory called results.txt, and writes our string to that file. Opening a file with option 'w' will override an existing file if there is one. You can use option 'a' to append to an existing file. You can also use option 'r+' to open a file for reading and writing.

<h4>Reading user input</h4>

We know how to read in data from a file. That's great! But what if we want to interact with the user in real time?

```{python, eval=FALSE}
name = raw_input("Please choose a cat name:\n")

if (name != "Captain Haddock") and (name != "Calvin"):
  print "That's not my cat!"
else:
  print "That is my cat!"
```

If we save this as a python file and run it, it will prompt the user for a string, and then output whether or not the string is one of my cats' names.

<h3>More about control statements</h3>

Let's consider expanding our program a little bit to give the user three guesses. One option would be to use a for loop to iterate through the code three times. This requires us to figure out a way to not repeat the prompt if the user has already correctly guessed one of my cats.

One option is to use a variable to store whether or not the user has already succeeded. At the top of the for loop, we'll check to see if the user has already guessed correctly, and if so, we won't do anything.

```{python,eval=FALSE}

success = False
for i in range(0,3):
  if success == False:                                        #Has the user succeeded yet?
    name = raw_input("Please choose a cat name:\n")
    if (name != "Captain Haddock") and (name != "Calvin"):
      print "That's not my cat!"
    else:
      print "That is my cat!"
      success = True                                          #Set the value of success to True since the user has guessed correctly
```

This is much easier to read. We can make it even more efficient however, by using *break* to end the for loop early if the user guesses correctly.

```{python,eval=FALSE}

for i in range(0,3):                                       #Has the user succeeded yet?
  name = raw_input("Please choose a cat name:\n")
  if (name != "Captain Haddock") and (name != "Calvin"):
    print "That's not my cat!"
  else:
    print "That is my cat!" 
    break
```

But what if we don't know how many chances we want to give the user? What if we want the program to run until they guess correctly?

<h4>While loops</h4>

There's another kind of control loop in Python that makes this easy. It's called a while loop.

```{python,eval=FALSE}
while:
  name = raw_input("Please choose a cat name:\n")
  if (name != "Captain Haddock") and (name != "Calvin"):
    print "That's not my cat!"
  else:
    print "That is my cat!" 
    break
```

Question: What happens if we forget to put in the break statement?

<h3>Dictionaries</h3>

Dictionaries are the bread and butter of Python programming. 

A dictionary is a data type that maps *keys* to *values*. 

What is a key? Anything that is immutable can be a key (strings, numeric types, tuples containing immutable values...). Within a dictionary, keys are unique.

Values do not need to be immutable. In fact, in the first lab, you'll probably use a dictionary that stores string:dictionary pairs.

```{python}
d = {'Harry Potter':'Gryffindor','Luna Lovegood':'Ravenclaw'}
d['Penelope Clearwater'] = 'Hufflepuff'
print(d)
```

There are several ways to access the contents of a dictionary. 

You can use the keys() or values() method to get a list of keys or values.

You can also use items() to get a list of key:value pairs.

```{python}
d = {'Harry Potter':'Gryffindor','Luna Lovegood':'Ravenclaw'}
for k in d.keys():
  print k
for v in d.values():
  print v
```

You can update the value associated with a key using the familiar bracket syntax.

```{python}
d = {'Harry Potter':'Gryffindor','Luna Lovegood':'Ravenclaw'}
d['Harry Potter'] = 'Slytherin'
print(d['Harry Potter'])
```

Plain old Python dictionaries will throw an error if you try to access a key that is not in a dictionary. 

```{python, eval=FALSE}
d = {'Harry Potter':'Gryffindor','Luna Lovegood':'Ravenclaw'}
print d['Ginny Weasley']
```

However, there is a data structure in the collections library called a Default Dict that solves the problem of having to initialize keys before accessing them.

The first argument to the defaultdict() constructor is the type of the values being stored.

```{python}
from collections import defaultdict

d = defaultdict(str)
d['Harry Potter'] = 'Gryffindor'
print "Harry Potter's house is: ", d['Harry Potter']
print "Ginny Weasley's house is: ", d['Ginny Weasley']
```

<h3>Functions</h3>

Let's think about how to write a program that is slightly more complicated than the cat guessing game we considered earlier. We're going to write a program that prompts the user for a list of words and a block of text, and counts how many times each of the words appears in the text (that is, count the *tokens*).

Let's break this problem down into tasks:

1. Ask the user for the name of the text file.
2. Ask the user for a list of words.
3. Count how many times each word appears in the text.
4. Report the results to the user.

That seems pretty simple! The first thing to ask ourselves, though, is when the program should quit. Should it only run once? Or should it wait until the user asks it to quit?

Let's write the program so that it runs until the user types "quit". We can modify our task list slightly to reflect this.

1. Give the user two choices: (1) count words or (2) quit
2. Ask the user for the name of the text file.
3. Ask the user for a list of words.
4. Count how many times each word appears in the text.
5. Report the results to the user.

Okay, let's tackle the first task first. We'll write a while loop that asks the user to pick an option, and quits if that option is 3.

```{python, eval=FALSE}

print "Hello! This is a word count program."

quit = False
while quit == False:
	print "Please pick an option: "
	print "1. Run word count"
	print "2. Quit"
	choice = int(raw_input("Your choice is: ")) #Remember to convert the input to an integer if you're comparing it to an integer!
	if choice == 2:
		print "Goodbye!"
		quit = True
	#GET USER INPUT
	#DO WORD COUNT
	#REPORT RESULTS
```

So far so good. Our program quits on demand, but otherwise it doesn't do anything.

If the user picks Option 1, we need to ask them for a file name.

```{python, eval=FALSE}

print "Hello! This is a word count program."

quit = False
while quit == False:	
  print "Please pick an option: "
	print "1. Run word count"
	print "2. Quit"
	choice = int(raw_input("Your choice is: ")) #Remember to convert the input to an integer if you're comparing it to an integer!
	if choice == 2:
		print "Thanks for playing!"
		quit = True
	else:
	  f = raw_input("File name: ")
	  wordString = raw_input("Words to count: ")
	  #RUN WORD COUNT
	  #REPORT RESULTS
```

Okay, so far we've handled the user input stuff. Now for the substance of our program. 

Let's think about how to do the word count. This piece of the program can be defined as follows:

Given a list of words and a block of text, count how many times each word appears in the text.
  
Now a human might go about this word by word, scanning the text and calculating the sum for each word. This involves looping through the text once for each word in the list. 

We're going to do something slightly different: we're going to separate the text into words and enter each word into a dictionary that keeps track of how many times it appears. Then, we'll simply print out the dictionary entries for each word in the list at the end. 

Although we create a dictionary entry for a bunch of words that we never see, we only have to go through the text once.

```{python}
from collections import defaultdict

text = "It was the best of times, it was the worst of times."
textList = text.split(" ")
d = defaultdict(int)
for t in textList:
  old = d[t]
  d[t] = old+1
print(d) #Notice that because we haven't normalized punctuation and capitalization, 'It' and 'it' are counted separately!
```

We've produced a word count dictionary for the text given above. But we really want to write a *function* that takes an arbitrary string.

Here's how we define a function in Python:

```{python}
from collections import defaultdict

###############################################################

def wordcount(text): 	#We name the arguments to the function in the parentheses
  text = "It was the best of times, it was the worst of times."
  textList = text.split(" ")
  d = defaultdict(int)
  for t in textList:
    old = d[t]
    d[t] = old+1
  return(d)
###############################################################

text = "It was the best of times, it was the worst of times."
counts = wordcount(text)
print(counts)
```

I've used the line of # characters to demarcate the end of the function (of course, the indentation level also shows us the end). Since # is the character used for comments, you can break up long programs into chunks this way.

Now we have all the pieces to write our word-count program.

It's conventional to put the body of your program inside a function called *main*.

You should always write a comment at the top of the file describing the file. It's generally good practice to put a comment by each function definition as well.

```{python, eval=FALSE}
"""
Author: Carolyn Anderson
Date: 9/15/17

This is a word-count program for Lecture 2.

Input: 	a list of words to count; a filename containing text to search
Output: a count per word of how many times the word occurs
"""

from collections import defaultdict


def main():

	print "Hello! This is a word count program."

	quit = False
	while quit == False:
		print "Please pick an option: "
		print "1. Run word count"
		print "2. Quit"
		choice = int(raw_input("Your choice is: ")) #Remember to convert the input to an integer if you're comparing it to an integer!
		if choice == 2:
			print "Goodbye!"
			quit = True
		else:
			filename = raw_input("File name: ")
			f = file(filename,"r")
			text = f.read()
			wordString = raw_input("Words to count: ")
			counts = wordcount(text)
			printResults(counts,wordString)

###############################################################

#Produces a dictionary containing token counts for each word in text

def wordcount(text): 	#We name the arguments to the function in the parentheses
  text = "It was the best of times, it was the worst of times."
  textList = text.split(" ")
  d = defaultdict(int)
  for t in textList:
    old = d[t]
    d[t] = old+1
  return(d)

###############################################################

#Prints the word counts found in counts for each white-space separated word in wordString

def printResults(counts,wordString):
	words = wordString.split(",")
	for w in words:
		w = w.strip()
		if w in counts:
			print w, counts[w]
		else:
			print w, 0

###############################################################

main()
```
