---
title: 'Programming in Python: Lecture 3'
author: "Carolyn Jane Anderson"
date: "9/22/2017"
output: html_document
---

```{r,echo=FALSE}
library(knitr)
opts_chunk$set(engine = 'python',engine.path="/usr/local/bin/python2")
```

Today we're going to learn about regular expressions.

#WARMUP EXERCISE

<h2>Regular expressions</h2>

Regular expressions are all about pattern-matching. They are called *regular expressions* because the basic atomics and operations form a *regular language*. However, regular expressions in many languages, including Python, have expanded functionality so that they are no longer regular.

<h3>Regular expression syntax</h3>

<h4>Character classes</h4>

. : any character except newline

\\w : word

\\d : digit

\\s : whitespace

\\t : tab

\\n : newline

<h4>Quantifiers</h4>

\* : 0 or more

\+ : 1 or more

? : 0 or 1

{n} : exactly n

<h4>Anchors</h4>

\^ : start of string

\$ : end of string

<h4>Sets</h4>

[ ] : set

[^ ] : complement of set

\| : or

[ - ] : range

```{python}
import re

s = 'address: 33 Peachtree St.'

m = re.search(r'[0-9]{1}', s) #Find first digit in string
print m.group(0)

n = re.search(r'.*',s) #Find sequence of 0 or more characters
print n.group(0)

print re.search(r'[a-z]',s).group(0) #Find lowercase letter

print re.search(r'[^aA-zZ]+',s).group(0) #Find sequence of non-letters
```

<h3>Regex methods</h3>

There are four methods for regexes.  

You can use match() to check if the beginning of the string matches the regex.

```{python}
import re

s = 'address: 33 Peachtree St.'

print re.match(r'[0-9]{1}', s)
print re.match(r'[a-z]{1}', s).group()
```

You can use search() to try to match the string at any position.

```{python}
import re

s = 'address: 33 Peachtree St.'

print re.search(r'[0-9]{1}', s).group()
print re.search(r'[a-z]{1}', s).group()
```

You can use findall()	to find all substrings where the RE matches. findall() returns all matches as a list.

```{python}
import re

s = 'address: 33 Peachtree St. Apt. 1079'

m = re.findall(r'[0-9]{1}', s) #Find first digit in string
for i in m:
  print i
```

Lastly, finditer(), like findall(), picks out all matching substrings, but it returns them as an interator rather than a list.

<h3>Match object methods</h3>

I've been using group() to get the string matched by search().

There are a few more methods you can use to get different information from the match object.

To return the starting index of the match, use start().

```{python}
import re

s = 'address: 33 Peachtree St.'

print re.search(r'[0-9]{1}', s).start()
print re.search(r'[a-z]{1}', s).start()
```

To get the ending index of the match, use end().

```{python}
import re

s = 'address: 33 Peachtree St.'

print re.search(r'[0-9]{2}', s).end()
print re.search(r'[a-z]{2}', s).end()
```

Last, span() returns a tuple containing the start and end indices of the match.

```{python}
import re

s = 'address: 33 Peachtree St.'

print re.search(r'[0-9]{2}', s).span()
print re.search(r'[a-z]{2}', s).span()
```

<h3>Exercise: finding phone numbers</h3>

Can you write a regex that matches phone numbers?

First we'll assume that each phone number is of the format (413)-555-3091, where the area code is given in parentheses, and hyphens are used to separate the blocks of digits.

Now let's try to be a little more flexible. How many of the valid phone numbers below can you capture, without capturing any of the invalid ones?

You can find the phone numbers in numbers.txt.

```{python}
f = file("/Users/carolyn/Documents/UMass/CogMod/Ling692c/lecture 3/numbers.txt","r")
print f.read()
```

I've written you an evaluation program in phonetest.py. This program takes two command-line arguments: your regular expression, and the name of the file of phone numbers.

For example:

python phonetest.py '^a' numbers.txt

The program prints out a score indicating what fraction of phone numbers you correctly identified. It also prints out the phone numbers that your regex failed to correctly classify (both false negatives and false positives).

I wrote a regex that catches all but two of the numbers: 

5550-0100

1-100-0101

Why are these cases problematic?

What would we have to do to exclude these bad numbers?

For many applications, regular expressions are a useful tool to catch the majority of cases, but it may not make sense to spend the time to consider every last case.

<h3>Capturing groups</h3>

There's one other aspect of regular expressions that I haven't shown you. This is the non-regular feature of most implementations of regular expressions: capturing groups.

Capturing groups is a way of giving regular expressions memory. The parentheses we used to group characters together above actually does a little more work than just making scope explicit.

Parentheses actually define groups, which can be referred to using *backreferences*.

```{python}
import re

fooafoo = re.compile(r'(\w)a\1')
s = 'ana nan bad dad ab banana.'
r = re.findall(fooafoo,s)
print r
```

Here, the \\1 refers to the first group of the expression: whichever character was matched by \\w. The regex above matches sequences where the same character appears before and after an a.

You can also use the group syntax to define a *lookahead* assertion. These are used to match something in the context of an expression without capturing anything but the expression.

You can write both positive and negative lookaheads. 

Let's consider an example where we are matching filenames.

```{python}
import re

r = re.compile(r'.*[.].*$')
files = ['foo.txt','foo.jar','foo.jpeg']
for f in files:
  res = re.search(r,f)
  if res is not None:
    print res.group()
```

It's very easy to match a filename: we simply accept a sequence of characters, followed by a period, followed by another sequence of characters and line end character.

(Note that we wrap the period character in a set since period is a special character in the regex syntax.)

However, it's not so easy to write an expression that recognizes all file types except one. For instance, say that we want to exclude just .jar files. 

We can start by excluding file extensions that start with 'j'.

```{python}
import re

r = re.compile(r'.*[.][^j]*$') 
files = ['foo.txt','foo.jar','foo.jpeg']
for f in files:
  res = re.search(r,f)
  if res is not None:
    print res.group()
```

Of course, this is too liberal, because we end up excluding jpeg files as well.

Instead, we can use a negative lookahead to specify an expression that we don't want to match.

```{python}
import re

r = re.compile(r'.*[.](?!jar).*$')
files = ['foo.txt','foo.jar','foo.jpeg']
for f in files:
  res = re.search(r,f)
  if res is not None:
    print res.group()
```

You can also use a positive lookahead to specify the characters that follow your target expression.

For instance, you might want to get the filename as a string without the extension following.

If you knew the file extension, you could use string.find in base Python, which is generally faster than a regular expression.

```{python}
file = "linguistics.is.cool.txt"
ext = file.find(".txt")
filename = file[0:ext]
print filename
```

However, if you don't know the file extension, you can use a positive lookahead to match a substring that is followed by a period plus a sequence of characters plus the line end character.

```{python}
import re

file = "linguistics.is.cool.txt"
r = re.compile(r'.*(?=\.[a-z]+$)')
res = re.search(r,file)
if res is not None:
    print res.group()
```

<h2>Regular Expression Practice</h2>

That's about all I want to tell you about regular expressions! You can use them to replace substrings as well as just find them, but I'll let you investigate that on your own.

Now we're going to practice what we learned on some text. 

<h4>Task: write a regular expression to capture as many of the proper names in names.txt as possible</h4>

```{python}
f = file("/Users/carolyn/Documents/UMass/CogMod/Ling692c/lecture 3/names.txt","r")
print f.read()
```
